sections:
  - Цель работы:
      text: >
        Проверка гипотезы о соответствии распределения экспериментальных
        данных нормальному закону. Изучение критерия Хи-квадрат
        (критерия Пирсона) и его реализаций в Matlab и Python.
  - Задание
  - Результат выполнения работы:
      img: 2
  - Исходный код:
    - code
  - Выводы
pages: 3