department_number: 43
course_name: "ИНФОРМАЦИОННЫЕ ТЕХНОЛОГИИ"
report_name: "СОЗДАНИЕ ПОЛЬЗОВАТЕЛЬСКИХ ФУНКЦИЙ В ПРИЛОЖЕНИИ EXCEL"
report_number: 1
teacher:
  name: "М.Д. Поляк"
  position: "ст. преп."